[package]
name = "blog_os"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


# 解决 eh_personality
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
